# Generated by Django 2.1.5 on 2019-01-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='protocol',
        ),
        migrations.AddField(
            model_name='project',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Protocol'),
        ),
    ]
