# Generated by Django 2.1.5 on 2019-01-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190107_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Progress'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='securitytype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
