# Generated by Django 2.1.5 on 2019-01-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscribemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_kr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_kr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Progress'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Protocol'),
        ),
    ]
