# Generated by Django 2.1.5 on 2019-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190110_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribemail',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
