# Generated by Django 2.1.5 on 2019-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190110_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securitytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
