# Generated by Django 2.1.5 on 2019-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190111_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemail',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
